### ISSUE TITLE
[BOUNTY]: Get this library working

### ISSUE THREAD

**Issue by jziggas** [swrpg-online/react-dice#1]
This library is not currently working. I am willing to pay a bounty for a React expert to help get it working. Leave a note in this issue if interested!

**Comment by aybanda** [comment]
Hey @jziggas interested in attempting this 
how much bounty can I expect in case if I resolve this?

**Comment by jziggas** [comment]
I’m curious how you find this repository? There is an error with loading the SVG/PNG assets from @swrpg-online/art. I am assuming the problem is simple but I’m not familiar enough with React yet to understand how assets should be imported. Offering $50 for a solution unless you can convince me that the issue is more complex.

**Comment by aybanda** [comment]
I was looking for open bounties where I can contribute, I will keep you updated if I encounter any complex issues.

**Comment by aybanda** [comment]
I've identified the core issue with the asset loading from @swrpg-online/art. The problem requires proper bundling and dynamic loading in React, not just simple imports.
I've already fixed the component structure and validation, but the asset loading needs a complete solution that handles bundling and dynamic loading across environments.
I can implement a robust solution for $100 that will work reliably in all environments. Let me know If that works.

**Comment by aybanda** [comment]
Hey @jziggas  I've fixed the issue. You can check out the PR and test it yourself. The library looks good now.
If everything looks good to you and you'd like to proceed with the bounty payment, you can do so through my GitHub Sponsors page: https://github.com/sponsors/aybanda 

Let me know if you'd like any changes or have any questions about the implementation!

**Comment by jziggas** [comment]
Thanks @aybanda. I already followed through with your sponsor page. Will review the changes later and if I have any questions I might add them here.

**Comment by jziggas** [comment]
@aybanda I've imported @swrpg-online/react-dice@0.4.2 (with your changes) into a small sandbox app and still don't see an asset loading:

<img width="272" alt="Image" src="https://github.com/user-attachments/assets/19c36306-515e-43a0-95b6-db444d88f3e6" />

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/9d18aedb-50c0-4d86-a1d7-636322f51cfa" />

<img width="355" alt="Image" src="https://github.com/user-attachments/assets/8e1bc6f0-b702-40ef-bb02-8557d461722c" />

I see that `const imagePath = constructImagePath(type, face, theme, format, variant);` evaluates to `@swrpg-online/art/dice/numeric/white-arabic/D20-01-Arabic-White.svg` which seems like a correct asset path?

What else is missing?

**Comment by aybanda** [comment]
The path construction is correct, but we need to make sure the @swrpg-online/art package is properly set up in your sandbox app. Could you please:
1.Verify that @swrpg-online/art is installed in your sandbox app
npm install @swrpg-online/art
2.If you're using a bundler (like webpack or vite), make sure it's configured to handle assets from node_modules

**Comment by jziggas** [comment]
@aybanda Maybe a lack of bundler is the problem as it is just using `react-scripts start` to run. You can see in the above screenshot that `"@swrpg-online/art"` is already installed in the package.json, but I imagine it would also exist in node_modules as a dependency to react-dice as well.

Could you provide a very minimal example with Vite that shows the component loading? It could be as simple as `<Die type="d20" face={20} />` with whatever correct bundler configuration is needed.

**Comment by aybanda** [comment]
<img width="799" alt="Image" src="https://github.com/user-attachments/assets/4df14759-c507-4169-bb9f-4eacffe3fd4c" />
Set up Vite to handle SVG assets from the @swrpg-online/art package

**Comment by aybanda** [comment]
The key was configuring Vite to properly handle the SVG assets from the `@swrpg-online/art` package. The `vite-plugin-svgr` plugin and the alias configuration ensure that the SVG files are properly imported and bundled.

You can see the d20 die rendering correctly and the roll button working to update the face value. The same setup works for other dice types (d6, narrative dice, etc.) as well.

**Comment by jziggas** [comment]
Thank you. It's still not working but I must be close. Let me just show you my minimal example.

```index.html
<!DOCTYPE html>
<html lang="en">
  <body>
    <div id="root"></div>
    <script type="module" src="/src/index.jsx"></script>
  </body>
</html> 
```

```index.jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
); 
```

```App.jsx
import React from 'react';
import { Die } from '@swrpg-online/react-dice';
import './App.css';

function App() {
  return (
    <Die type="d20" face={20} />
  );
}

export default App; 
```

```vite.config.js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import svgr from 'vite-plugin-svgr';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    svgr({ 
      include: '**/*.svg',
    }),
  ],
  // Serve files directly from node_modules
  server: {
    fs: {
      // Allow serving files from one level up (including node_modules)
      allow: ['..']
    }
  },
  // Don't inline assets as base64
  build: {
    assetsInlineLimit: 0,
  },
  // Make @swrpg-online/art resolve to the actual node_modules path
  resolve: {
    alias: {
      '@swrpg-online/art': path.resolve(__dirname, 'node_modules/@swrpg-online/art')
    }
  }
}); 
```

Is there something different in your own vite config?

**Comment by aybanda** [comment]
Yes, there are a few key differences in our Vite config that might be causing the issue.
Here's what I suggest changing in your vite.config.js:

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';

export default defineConfig({
  plugins: [
    react(),
    svgr()
  ],
  resolve: {
    alias: {
      '@swrpg-online/art': '@swrpg-online/art'
    }
  },
  assetsInclude: ['**/*.svg']
});

make sure your index.html is in the root

**Comment by jziggas** [comment]
Using the vite configuration you provided is also not rendering an asset :(

**Comment by jziggas** [comment]
I'm able to get a an asset rendered with something like 
```
import d20Face20Svg from '../node_modules/@swrpg-online/art/dice/numeric/white-arabic/D20-20-Arabic-White.svg';
<img src={d20Face20Svg} alt="D20 showing 20" />
```
While the `Die` component continues not to render. So it seems like Vite can can resolve the `img` tag at build time but cannot handle `Die` constructing image paths at runtime.

**Comment by jziggas** [comment]
Closing this issue as I believe I've solved the loading and added documentation to the readme as a result.
